image:
  file: .gitpod.Dockerfile

ports:
  - port: 8000-9000
    onOpen: open-preview

tasks:
  - name: Setup Dev Env
    init: |
      # update conda to latest version
      conda update -y -n base -c conda-forge conda
      # create the conda env with dependencies
      conda create -y -n oscb python=3.10 ipykernel notebook numpy pandas numba bokeh nltk
      conda activate oscb
      # register this conda env as a NB kernel spec
      python -m ipykernel install --name oscb --user
    command: |
      # activate the conda env
      conda activate oscb
      # trust NBs
      jupyter trust Walkthrough.ipynb
      # start notebook server
      #    https://github.com/gitpod-io/gitpod/issues/758#issuecomment-525706696
      jupyter notebook --NotebookApp.allow_origin=\'$(gp url 8888)\'

vscode:
  extensions:
    - ms-python.python

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
